update.json
This can be put in now as the mod checks the update.json on master, and not other branches. After merging, this will be the official update.json and people will get a notification to update.
=> Fix update.json for 0.86d

src/main/java/ValkyrienWarfareControl/ValkyrienWarfareControlMod.java
=> Fix calls to Minecraft.getMinecraft().mcDataDir

src/main/java/ValkyrienWarfareBase/Command/PhysSettingsCommand.java
Because apparently I didn't fix it well enough before. This should be faster too :D
=> Fix /physSettings again

src/main/java/ValkyrienWarfareBase/Command/PhysSettingsCommand.java
Something about this caused a Jenkins failure, I'm reverting in the hopes to find out why
=> Revert "Fix /physSettings again"

src/main/java/ValkyrienWarfareBase/API/EnumChangeOwnerResult.java, src/main/java/ValkyrienWarfareBase/PhysicsManagement/PhysicsObject.java, src/main/java/ValkyrienWarfareControl/Item/ItemShipStealer.java
I don't know if this works, i don't have anybody but myself to test it with.
=> Hopefully fix the airship stealer

src/main/java/ValkyrienWarfareBase/EventsCommon.java
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2761225-valkyrien-warfare-airships-physics-subworlds-and?comment=348
=> Fix NullPointer

src/main/java/ValkyrienWarfareControl/Block/BlockShipPilotsChair.java, src/main/java/ValkyrienWarfareControl/Piloting/ShipPilotingController.java
This should fix airship movemnt based on chair placement
=> Fix Pilot's chair

src/main/java/ValkyrienWarfareBase/Collision/EntityCollisionInjector.java, src/main/java/ValkyrienWarfareBase/CoreMod/CallRunner.java, src/main/java/ValkyrienWarfareBase/CoreMod/EntityDraggable.java, src/main/java/ValkyrienWarfareBase/EventsClient.java, src/main/java/ValkyrienWarfareBase/EventsCommon.java, src/main/java/ValkyrienWarfareBase/PhysicsManagement/PhysicsObject.java, src/main/java/ValkyrienWarfareBase/PhysicsManagement/PhysicsTickHandler.java
Things like drag and persistant velocity are found here, as well as fixing a variety of issues with the player being around multiple ships at once.
=> Rewrote the Entity movement system for Ships

src/main/java/ValkyrienWarfareBase/BlockPhysicsRegistration.java, src/main/java/ValkyrienWarfareBase/EventsCommon.java, src/main/java/ValkyrienWarfareBase/Interaction/CustomNetHandlerPlayServer.java, src/main/java/ValkyrienWarfareBase/Physics/PhysicsCalculations.java, src/main/java/ValkyrienWarfareBase/PhysicsManagement/PhysicsObject.java, src/main/java/ValkyrienWarfareBase/Relocation/ShipBlockPosFinder.java, src/main/java/ValkyrienWarfareBase/ValkyrienWarfareMod.java
=> Prevent infusing water and lava, and add a simple way of blocking other blocks should ne need arise.

src/main/java/valkyrienwarfare/mod/client/gui/GuiPhysicsInfuser.java, src/main/java/valkyrienwarfare/mod/common/ValkyrienWarfareMod.java, src/main/java/valkyrienwarfare/mod/common/block/BlockPhysicsInfuser.java, src/main/java/valkyrienwarfare/mod/common/block/BlockPhysicsInfuserCreative.java, src/main/java/valkyrienwarfare/mod/common/physics/management/PhysicsObject.java, src/main/java/valkyrienwarfare/mod/common/physmanagement/chunk/DimensionPhysicsChunkManager.java
Fixing a couple of miscellaneous code smell & issues
=> Fixes - refactoring

src/main/java/valkyrienwarfare/mixin/client/renderer/MixinViewFrustum.java, src/main/java/valkyrienwarfare/mod/common/ValkyrienWarfareMod.java, update.json
=> add update.json

src/main/java/valkyrienwarfare/mod/common/config/VWConfig.java, src/main/java/valkyrienwarfare/mod/common/physmanagement/relocation/ShipSpawnDetector.java
See: #272 
This branch makes the ShipSpawnDetector blacklist configurable.
=> Make the ShipSpawnDetector blacklist configurable. Closes #272

src/main/java/valkyrienwarfare/addon/control/BlocksValkyrienWarfareControl.java, src/main/java/valkyrienwarfare/mod/common/ValkyrienWarfareMod.java, src/main/java/valkyrienwarfare/mod/common/config/VWConfig.java
See: #288 
The old engine's power levels are now configurable (requires restart)
=> Make engine config configurable. Closes #288

src/main/java/valkyrienwarfare/addon/control/block/BlockThrustRelay.java
=> Make Network Control Relay placeable on any block, in any orientation.

src/main/java/org/valkyrienskies/addon/control/renderer/GearboxTileEntityRenderer.java
=> bro u forgot about model renaming

src/main/java/com/best108/atom_animation_reader/impl/BasicDagNodeRenderer.java, src/main/java/org/valkyrienskies/addon/control/block/multiblocks/ITileEntityMultiblockPart.java, src/main/java/org/valkyrienskies/addon/control/block/multiblocks/TileEntityGiantPropellerPart.java, src/main/java/org/valkyrienskies/addon/control/block/multiblocks/TileEntityRudderPart.java, src/main/java/org/valkyrienskies/addon/control/block/multiblocks/TileEntityValkyriumCompressorPart.java, src/main/java/org/valkyrienskies/addon/control/block/multiblocks/TileEntityValkyriumEnginePart.java, src/main/java/org/valkyrienskies/addon/control/item/ItemWrench.java, src/main/java/org/valkyrienskies/addon/control/piloting/PilotControlsMessageHandler.java, src/main/java/org/valkyrienskies/addon/control/tileentity/TileEntityNetworkRelay.java, src/main/java/org/valkyrienskies/addon/world/capability/ImplCapabilityAntiGravity.java, src/main/java/org/valkyrienskies/mixin/client/renderer/MixinEntityRenderer.java, src/main/java/org/valkyrienskies/mixin/client/renderer/entity/MixinRenderManager.java, src/main/java/org/valkyrienskies/mod/common/config/VSConfig.java, src/main/java/org/valkyrienskies/mod/common/physics/management/ShipTransformationBuffer.java, src/main/resources/assets/vs_control/lang/en_US.lang
=> Add modeless wrench config option

src/main/java/org/valkyrienskies/addon/control/renderer/BasicNodeTileEntityRenderer.java
fix massive log spam oops printf was left in
=> oops pls merge rn

src/main/resources/assets/valkyrienskies/lang/zh_CN.lang, src/main/resources/assets/valkyrienwarfareoc/lang/zh_CN.lang, src/main/resources/assets/vs_control/lang/zh_CN.lang, src/main/resources/assets/vs_world/lang/zh_CN.lang
Added Chinese translation for master
=> Chinese Translations

src/main/resources/assets/valkyrienskies/lang/uk_UKR.lang
=> added Ukrainian translation

src/main/java/org/valkyrienskies/addon/world/worldgen/ValkyrienSkiesWorldGen.java, src/main/java/org/valkyrienskies/mod/common/config/VSConfig.java
Quick option I was looking for in my modpack that I wanted to add.
=> Added config option for Valkyrium ore spawn rate

src/main/java/org/valkyrienskies/mod/common/config/VSConfig.java
engines must be replaced after changing force
dont know if it will let me add a comment for the whole class
=> note on engine power setting
